version: "3.9"

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend (Express + Node.js)
  server:
    build: ./server
    container_name: todo_server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend (React + Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_BASE_URL: http://server:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
